-- Create custom_inquiries table in Supabase
CREATE TABLE IF NOT EXISTS public.custom_inquiries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  delivery_date DATE NOT NULL,
  requirements TEXT NOT NULL,
  image_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Disable RLS to allow direct public inserts from the website form
ALTER TABLE public.custom_inquiries DISABLE ROW LEVEL SECURITY;
